sudo: false
language: node_js
node_js:
- 5.0.0
install:
- npm install
before_script:
- npm install
script:
- npm run-script travis
addons:
  sauce_connect: true
env:
  global:
  - secure: NjtizaVe5JFjrzYp4ODVj6I+rXTIBdOYRhuKecYF5aV9J8D6I3aAkmolMz7OqjoLejGrmck8juk0Oggb9QP25dZd1/trIB1oVuCuapJaT6J1LL0fdOa72+ohmG1l8CwGp94ebrH1nTl47oWu+B1Aqyg2OkVrXv28lhC0rFV0p87Zp1viBNaNjRkfZXWyVEvs2Xne1nQKGbsrpQNfeUHBPR4gVbO9ws5Rv4qGR4XA/Uggo5Zp9iKwh9MRLcSgKBSGdyTgRVb2OVZ7eZT5UqjnFWUL7Tbj5CVB4BMvXb6KiEjaLpNTnAVyDvnnP8uP98XLMniBVKhnm7WQsNbvgb4ViP/XJDNC/vLWFqWyryivc95TCKfhr9FOSjMWxwKocyKS/XA7YE9YMO4rvefFhj67OWY1pi+l8dQCelxwK7IaIPcLm5ewtba9vJQFIbVq8G6+w4Ydsk+/rX9NogkTpUdacRIPMDRBfUL0Ovcmj00LMNxpTOYFgQxQliydOYSG92oj0gJafVtfsc41LRbK5VPgOO82hBGNylcPMUBIkWgrQQQZmiez6rql/HaEAQUaoUg25XrTfykXqdxUwJnnaXuRXen5uskC2XYpj9X369AVOomKhHDOczhsLST+cjmBRQFbGeoichNW8Es8baNwCyGIsvMfnORuSrfLvTGmiofzwYo=
  - secure: lGzkXZPWhvc9eYb9RYzHOcgaZrb929r4UH0PCwiGZ5NENKzcvag2ykWUK2uzQZ4ChdCKG8WOM3Gs4fsdfmIAh/1eu7eRDgRCuIqOmjy4pGWFzpoZjkbMHC7BKJ2fy+3EQxTcH3+nzbb559qGCRSC5BsjiAbP3zHrCWt+X8d2bofecBl4wk7wTPDh1sVbJ0wgeQIeb/ubafcmFxVPkhqXlaqq+UdDGSQgyQYDHe96BQACQ7NVruyPtJcjv188hOf+ADeldPMsMmWcTNQRek0Jw9Cf2Qkgf3TPtQTho35qk+V8RL+93LFRE4CL4Er54tJ1EaifRjU1qMDwPRW4k3vcZdcQINSx87j7BAE5SfFXYDAaH/xnMKWscaAAmUr7XQ4C5qmjDefttnDb7kHvHrG9fWdOneMJl7iNFHTx42IyW+aCGjKk+Yzkr9TemEEai0vtngNHjl+5t3iffaHp4DFAOmG3WAAv75pS4gapeFV6JcjpOzwzdrfiHx72F0RLjLw6ZjieW7XBGlJU3gcyw42U7P8v79FHTdNDrtARfJRalnMgDLQaFmmyiGt4jxD3f+itM3BJkPPADP+oJ/za0kzyWSjJQ6hNAh45ueQyBVbwYLZZNzeSpor5+GcK79BGeKREhQrrhsR/IE6JRtU+ZlKdj6PtG42Gi9AUd864/U+nemI=
notifications:
  email:
    on_success: always
    on_failure: always
