sudo: false
language: node_js
node_js:
- 5.0.0
install:
- npm install
before_script:
- npm install
script:
- npm run-script travis
addons:
  sauce_connect: true
env:
  global:
  - secure: v3VQk6K/6GuRbm5Koh/rNz4i6uKc5Cld1S1LdHHHFaISyWiFOm3BmY2Hc8CAfa/Ec9tME2b0tOwNJzb6ZBUDSdQxNIuIoPq7YsB8V6Sjcn6BJ8gItdCAkZER81+e+8NwJHLI+JCnMpBDRRoFg8g61Fy1MBK1aXNar5rHFSI480E0OpO079JTz5KheNkxRMxE7vhpGBxepe4UyLosCOKrs+WTP+0xq/X+5x+HlNjEZcMS9jRqz2NAB/w47QmuQ4Xk4OZePzv4JjZE98T5/gutwWEg5GKopzy8A5kOcx2s4wGFJVG6RUKz7ulqZmKIwn0lOk4Qv/KmH2cgtqY+1UTa73Xgj/mYIXV0jp2YE2Nbm+wfGzxAi4wvbpkkM6OpdJIrMrhbmsPiSChZO5CrSxIMgb2u9zo2Up+jJcbl0tQjDlZ6GRcK1ftcI/ZMAI2v75zo9oRl6DiTKN4Drmh0wIjj6eBhGjg2+cdSdc5Qpr0AXrhBEvWHUxclt31H3mKx9It1ra5ihIv9GOx/TSS0Nny7caE0lpjqTzShW6p1wvwT0MWPGLcL31hnAxdmAvfAGkQ8FCIwnWlVhGPlmh6Ouot+u4p972WjzqIt7wUF3u4YF+axxF5IqWfT10XnC6KYTqu88/3FtIvcQW7IU7wBJW+QsGzem761qik3vBJWRpF+If8=
  - secure: cKWFAE3FQ4/cmwzNryX036rWMjh2gVx6atSZN7TW2E3wHJj1MvWWMLUcJPfnZflBN8uJaLcJzwIgfHSIMLpFcdG46yKD7hFuYkpEA9DmkIoRYztjnCpvP2IcXZ9OrNz3NI22rAuKxKdtmBWgH1tqLtppkf6gWeELwPuEEle9IG8FDuhLYXjAMU2rdharOhIvVHdJjy25kqLMbsF7eu09FvKq/OJS6YFdarX2/syzbFhxrPye/gJEmrKJLPSFtJTLP2AEL4tKaezHWezo4P5BZ8UNmyEZ4TFdYIclxeSiufBMApr7BJJ9N3S/xQZRgICRTKM0PHPg0DcJBWWTyU4eHZ7Uw+WdjSla3TGh9i0XxIFJh2bxap4wHet/uogq6o9yq/GGNpjlEFLhpqZPwETASBKyncNbrVbTjHUbOJWaUxg3kZ4DHksTBvFcxlTF51uZQs8yStkpChq6P+q6glZQK9+2nXcvqhgOJ31JKXjRaArVvE1UXYYy26GkETfdJtBKqgaXmSzmrbwxLaPBY5MLSUeQb5Sdibgi5mK4mNNkphMzpIMC1cUx62NHvsT9Nw+RApbMNXWcR4QH8fVKKLfKrFbeeqdp8nw93sRvvvXi2LGrZiRqGbkWC8Ilk7tSzsdLP2wQJ/+dAvrQupwt7wHiHFcHeMDmJkfyLynzmdbLpKY=
notifications:
  email:
    on_success: always
    on_failure: always
