sudo: false
language: node_js
node_js:
- 5.0.0
install:
- npm install
before_script:
- npm install
script:
- npm run-script travis
addons:
  sauce_connect: true
env:
  global:
  - secure: 3SF61kTM5wljMbzMtgvU4yzf5rtC7UKIQO4N9LAj8zsJs9WsJvpswgHZ6Xs9gr6d1B/0Sauaeo7tScMzuMfqHFQI/KO//jfRZe2lHEnzlYc3/SJaGK1xpXr9F9q/1EmqX5+A+KCVKat1UXXmvKlt3AuEE5EBw7ds6awXGXdcGd/azDwyklbmRYSlQ38FplHNBQ5Dtyv956yLUSCP/RqrfgUeBC/M2BV/aMIkA42842aEGChFgXIEte5gtZwfNcXhc6eGcDRMPfhZK2r2ypUa/myE31QpeQ812dWb8y+/rGQWP/v2a7vku5pf0npc8lcSeuN6ZAlciQHrQfd/MOlMT7NFG+MPLTEpC/ey5zihpYsh+bAAn7rvQyCkzG9IFxBus3L1J/embNawKMqZAR5bttyMTEP1VMv9RSuT8UJA4R6JMG+26Rm6JabpSVWudUKzReekjgA8NN3Bvqk/xX1z4ijhF2mlTXbAJKsbSGYt1uk5ITjBP9/ykEJ4AGF2VgPHuEVLE7VlwGagaGlFfag/9jI0VTpuIUYWU/INoHMVbF1XxCDxk/9SwPcDkq/1C2DtqN58ZBi5NkDzotTNIJr/P26r3cVt3KlH9XXesxzO+SAU8dlxjOK7lvnQXHK7qBUA1PURKTHntORTGWWz3d3HqIdH8cy1D/8X+4S9m2L05vA=
  - secure: W7n6tU/E0GEGbwoyO2f6dSfVJbmvBz6F0nfummIUyCvg+ntDO7kMtFvVN9x/uW7y6YkMALeXL0fRRPxUWqp6whzWIGszaBED7lkf1I+9d4dcNWl4vlzwn+MygzP8MZLAHAb1MpruiUSmVZ5wp3Jw3NuFRT45AwYctRNTFjmB1Wd7A5o9gYTEV0fnjJFiBQ6T4e8k56SSpO6Y9LpOEG3XeRWbdbOwMTWGMORVFllLD/VGqimAyQGWAr0lnpHV1SFJ0myuHV9BUFMBcAM53Fkz/IY5CAHrAXoHAHdvxAHDL4WFAKLf8udkxazuPmPbonKD9asKz77NjVfN50pb0xWZ1vYXw1diIoc0LL0Ed7SKyBZyG1honHW5yI4KTg7AIl7oNqL+L2FfzkKkZHjEBXogLn6OOGQq6gu6+6slP5Atn85FIQ5OOmikQ17zUwrbL4Ew1ckLL9y9orXkjQmFrQnIAKU6W4teGssT7ZWAoIQY97+JRCmYd6Xh84qoT+L+szfC8wiPuL0lcPwVWQLzmxeVtnFsap+ngZ7R1r82GhaxYV9iIrPLZrWSXViFGU8n2Hp+PwVblGCTziRPGWbCeyFlvTYAo3LT1yJNLAA97qYaUKZYP2zZV9ygBtn09PAe3+m6rkJ2j0k5ARp68kzEPsPbvbIUNSgTqtdVcJ+nO14GzHY=
notifications:
  email:
    on_success: always
    on_failure: always
