title: ng-apimock
description: Node plugin that provides the ability to use scenario based api mocking for both local development and protractor testing
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
          - jekyll-mentions
